### ISSUE TITLE
out of memory error when updating an object

### ISSUE THREAD

**Issue by ethanhere** [memcached/memcached#455] opened 2019-02-11 21:52 UTC
We experience out of memory error when updating an object with bigger size:
2019-01-30 20:49:06,401 (http-nio-8080-exec-59) ERROR [com.nokia.solo.server.util.MemcachedCacheImpl] - Exception occurred while performing cas operation on memcached: MemcachedServerException: out of memory storing object,key=policy/POLICY-4726d860-dc06-4bf0-94ba-127a0e09d231
net.rubyeye.xmemcached.exception.MemcachedServerException: out of memory storing object,key=policy/POLICY-4726d860-dc06-4bf0-94ba-127a0e09d231
        at net.rubyeye.xmemcached.command.Command.decodeError(Command.java:262)
        at net.rubyeye.xmemcached.command.Command.decodeError(Command.java:279)
        at net.rubyeye.xmemcached.command.text.TextCASCommand.decode(TextCASCommand.java:83)
        at net.rubyeye.xmemcached.codec.MemcachedDecoder.decode0(MemcachedDecoder.java:61)
        at net.rubyeye.xmemcached.codec.MemcachedDecoder.decode(MemcachedDecoder.java:56)
        at com.google.code.yanf4j.nio.impl.NioTCPSession.decode(NioTCPSession.java:297)
        at com.google.code.yanf4j.nio.impl.NioTCPSession.decodeAndDispatch(NioTCPSession.java:237)
        at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:207)
        at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:196)
        at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:341)
        at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56)
        at com.google.code.yanf4j.nio.impl.NioController$ReadTask.run(NioController.java:110)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Shouldn't eviction take care of memory allocation?
What remediation can we try in this scenario?

**Comment by dormando** [comment] 2019-02-11 21:54
It normally does. What version of memcached server are you using and what are your start arguments?

**Comment by dormando** [comment] 2019-02-11 21:57
I think some clients can also incorrectly give OOM errors if you try to store an object larger than the item size limit (1 megabyte by default)

**Comment by ethanhere** [comment] 2019-02-11 22:00
VERSION 1.4.4
options:
PORT="11211"
USER="nobody"
MAXCONN="1024"
CACHESIZE="14336"
OPTIONS="-l 0.0.0.0"

**Comment by ethanhere** [comment] 2019-02-11 22:02
according to my telnet localhost 11211 and "stats cachedump" monitoring, when it behaves well:
the object is put to, let's say, slab 14;
then increase the object size then update,
it should put the object to slab 15, and slab 14 doesn't have it anymore

**Comment by dormando** [comment] 2019-02-11 22:12
If you upgrade to the latest version you shouldn't see that issue anymore, so long as your issue isn't that you are setting values larger than 1 megabyte.

The problem is a bit complicated to explain, but has to do with memcached's memory management. In short, if "slab class 15" has only 1 megabyte of memory available in its pool and two clients try to set a large value at the same time, one of them will get an OOM error. Versions 1.5.0 and later balance memory over time and have a few other fixes to avoid this problem.

**Comment by ethanhere** [comment] 2019-02-11 22:22
thanks for your input. but in my case, there is only one client. would the upgrade still work?

**Comment by dormando** [comment] 2019-02-11 22:26
very likely yes. besides that, 1.4.4 came out over 9 years ago and I can't support it. if you have the same or similar issue with the latest version I can debug it more easily, but odds are good the problem's been solved sometime in the last decade.

**Comment by dormando** [comment] 2019-02-14 01:06
@ethanhere I'm closing this out since I can't time travel and fix the bug in 1.4.4 :) If you get on a newer version and can reproduce feel free to open an issue about it. Thanks!

**Closed by dormando** 2019-02-14 01:06 UTC
