### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by mrozentsvayg** [memcached/memcached#377] opened 2018-05-08 01:35 UTC
Hi,

Experiencing an issue with the memory usage.
The memcached process resident size is significantly larger than the memory allocated to the slabs.
As it only grows, it apparently gets killed by OOM eventually (usually couple months in current setup)
`STAT limit_maxbytes 23068672000` doesn't actually help, as the RSS increases independently.

Memcached is exclusively running on a number of aws r4.xlarge instances with ~1.5k get/s over ~80k persistent tcp connections. Non-default parameters: -m 22000  -t 4

3 days uptime process (~7G RSS vs 3.5 of alloced):
```
$ echo stats | nc localhost 11211|egrep ' bytes '; echo 'stats slabs' | nc localhost 11211|egrep total_malloced; egrep -i rss /proc/`pidof memcached`/status ; echo -n Anon: ;sudo pmap -xx `pidof memcached`|egrep anon | awk 'BEGIN{s=0}{s+=$3} END{print s}'
STAT bytes 2452758519
STAT total_malloced 3687841792
VmRSS:   7003412 kB
Anon:7003180
```

soon-to-be-killed (process running >2mo):
```
$ echo stats | nc localhost 11211|egrep ' bytes '; echo 'stats slabs' | nc localhost 11211|egrep total_malloced; egrep -i rss /proc/`pidof memcached`/status ; echo -n Anon: ;sudo pmap -xx `pidof memcached`|egrep anon | awk 'BEGIN{s=0}{s+=$3} END{print s}'
STAT bytes 7909043757
STAT total_malloced 23068630896
VmRSS:  30135748 kB
Anon:30135880
```

It's reproducing on both legacy 1.4.14 ubuntu trusty version and latest compiled 1.5.7.

Any ideas?

Thanks.

[memcached.stats.txt](https://github.com/memcached/memcached/files/1981943/memcached.stats.txt)

**Comment by dormando** [comment] 2018-05-08 01:45
hey,

can you include output of 'stats settings' just for completeness?

it's not the hash table, since that's accounted for in stats and is small. I wonder if it's connection memory... there're a few buffers which don't end up in stats still. In the stats there're ~87k current connections, and I also see a good number of conn_yields, which happen when connections are handling a high number of requests at once. It does realloc if they get too big, but they can grow a bit and cause some fragmentation if done a lot.

Are you sending huge multigets from thousands of connections in parallel?

**Comment by dormando** [comment] 2018-05-08 08:16
It holds onto the connection structures and minimal buffer memory after disconnect, so once it's bloated a bit dc'ing stuff won't help.

Do you have some kind of daily/cron/infrequent job that would be doing that? You can't get a conn_yield unless 20 reqs come in all at once. These could be packed sets/gets/something. They all come into the server from a single network read.

What's the connection_structures value for your instance which was "about to be killed"? I don't think the first stats output was from that one. Your limit's about 1m but it looks like the younger instance had seen at most 91k. The first time an fd is seen it gets a connection structure allocated for it, then it hangs around.

If connection_structures is closer to the limit for the worse-off instances that might explain a lot of it. Something could be expanding the buffers below the HIGHWAT (8k for the read buffer). A couple k of buffers + a slightly inflated read buffer could be 5G+ of RAM just in connection structures. My guess then would be you have some periodic network events which cause connections to pile up until you end up in this situation.

I do hope to make the connection memory overhead a lot better in the coming months, but I feel like maybe your connection limit could just safely be set a lot lower.

**Comment by mrozentsvayg** [comment] 2018-05-08 18:46
Unfortunately it's only 136k for the instance of 83d uptime, attaching all the stats just in case.

[memcached.stats2.txt](https://github.com/memcached/memcached/files/1985099/memcached.stats2.txt)

I can't quite control all the requests, potentially it could be whatever originated by the legacy code.
Though by dumping traffic within 5 min, when heap has increased on ~500Kb (malloced didn't change):
```
Tue May  8 11:22:25 PDT 2018
STAT bytes 3070886691
STAT total_malloced 3687841792
VmRSS:   7230232 kB
Anon:7230436
```
```
Tue May  8 11:27:25 PDT 2018
STAT bytes 3063717993
STAT total_malloced 3687841792
VmRSS:   7230960 kB
Anon:7230976
```
we had 654634 requests out of which:
```
  64604 set
 133055 delete
 456975 get
```
and the distribution of the number of the keys requested:
```
      1 XXXXXXXXXXXXXX
      2 XXXXXXXXXX
      2 XXXXXXXXXXXXXXXXX
      5 XXXXXXXXX
      5 XXXXXXXXXXX
     11 XXXXXXX
     11 XXXXXXXX
     85 XXXXXX
    127 XXXXX
    425 XXXX
   3289 XXX
  37655 XX
 415357 X
```

**Comment by mrozentsvayg** [comment] 2018-05-08 21:39
> is that 415,357 keys in a single request?

it's a 415,357 single key gets; 37,655 gets of 2 keys and so on

> So, since this is reproducable in 1.5.7 I'm super interested in tracking it down... it could be a couple back and forths (a week or two or more) though, if that's okay? 

of course, no worries. glad to hear it's got some priority to be addressed

> Found a really old branch: https://github.com/dormando/memcached/commits/conn_accounting - I can update this a bit and we can start there, if you wouldn't mind deploying it. Should tell us pretty obviously if it's connection memory, at least.

should be fine, unless it affects the basic functionality or there's a huge performance impact

**Comment by dormando** [comment] 2018-05-08 21:45
Figured I had it backwards, thanks :) How long are your keys on average?

The patch won't affect anything. You'd have to be doing millions of ops/sec to notice. If I can get motivated enough to do thread local accounting, it won't affect anything at all. I'll ping back here once I have a minimalist patch.. at very least, if the memory doesn't show up as accounted for here, we'll know it's somewhere else. Though 1.4.14 had very few features compared to 1.5.x. I have a hard time imagining it could be anything else.

**Comment by mrozentsvayg** [comment] 2018-05-08 22:13
> How long are your keys on average?

it's 32 or 112 bytes, 50/50

**Comment by dormando** [comment] 2018-05-09 01:11
https://github.com/dormando/memcached/tree/conn_accounting2 - please give this branch a try. it adds a bunch of new stats counters, which you can watch to see which increase over time by how much.

iovec's use more memory than I was expecting... btw, ascii or binary protocol? Also, how many instances do you have?

thanks!

**Comment by mrozentsvayg** [comment] 2018-05-09 01:47
thanks, got it running on one instance.

> btw, ascii or binary protocol? Also, how many instances do you have?
ascii, running 2 clusters of 100 and 200 instances

**Comment by dormando** [comment] 2018-05-09 01:52
excellent. I was worried about you only having a few and thus this being painful :)

**Comment by mrozentsvayg** [comment] 2018-05-09 18:28
After 16h:
```
Wed May  9 10:59:38 PDT 2018
STAT bytes 2944140875
STAT total_malloced 3408920576
VmRSS:   5432360 kB
Anon:5432444
```
Heap is 2G larger, and the connections buffers and lists indeed using > 1.5G 
```
STAT conn_struct_bytes 45645312
STAT conn_wbuf_bytes 182581248
STAT conn_rbuf_bytes 471396354
STAT conn_ilist_bytes 142641600
STAT conn_slist_bytes 142641600
STAT conn_msghdr_bytes 49924560
STAT conn_iovlist_bytes 570566400
```
[stats.20180509105745.txt](https://github.com/memcached/memcached/files/1988930/stats.20180509105745.txt)

**Comment by dormando** [comment] 2018-05-09 18:41
looks like I typoed the conn_shrinks stat as a second conn_reallocs, but it looks right in the code. there're more up reallocs than shrinks, and I've also found in the code that slist has no HIGHWAT/shrink code :(.. however in your case ilist == slist, so there've been no ilist shrinks.
rbuf is ~double wbuf, so the up-allocs are most likely rbuf's.

I'm guessing you do actually need that many active connections? :) I think most of the folks I know who have that high connection count have much larger caches, so the percentage of memory used by connections is still relatively low.

Anyway; please keep an eye on it for a few more days and lets be sure there isn't something huge that's unaccounted for. I didn't mark every single allocation (and none of the extstore ones), so the percentage of "unknown" increase should drop from 25% as general allocation grows. If not, I guess we'll keep digging.

If the issue is indeed this: https://github.com/memcached/memcached/issues/328 - is the issue to track it, which notes some challenges. I can probably do something quickly with the knowledge that the "worst case" from it would be equal to today. Your best case would cut almost all of the memory usage outside of conn_struct_bytes though.

**Comment by mrozentsvayg** [comment] 2018-05-10 18:02
Day 2
the heap is now 1G more since yesterday (and larger than malloced on 3G):
```
Thu May 10 10:56:51 PDT 2018
STAT bytes 2985250185
STAT total_malloced 3492806656
VmRSS:   6400560 kB
Anon:6400888
```
while the connections structures increased for only 100M since yesterday(1.7G)

[stats.20180510105523.txt](https://github.com/memcached/memcached/files/1992729/stats.20180510105523.txt)

**Comment by dormando** [comment] 2018-05-10 18:40
Hmm interesting. There're a good number of reallocs so some of that could be fragmentation (which would level off over time), but the overall conn memory isn't going up all that much.

Problem is we're running out of things that allocate memory :) If slist isn't growing, the suffixlists shouldn't be either, unless they leak somehow. Are you running any kind of odd malloc or kernel or etc? Only other things that malloc are temporary, stats buffers/etc. That could cause some extra fragmentation if you're running something like "stats cachedump" or "stats items/slabs/etc" constantly... like every second from random threads.

I'll poke through and see about adding a few more counters today. If possible, should keep the current test instance running and start a second one today.

**Comment by dormando** [comment] 2018-05-10 20:14
Do you issue 'gets' (get with CAS) at all? I don't see any CAS operations, but some clients default to fetching the CAS value for some reason.

I'm guessing no, which wouldn't create any cache items for the one non-stats malloc I haven't instrumented.

**Comment by mrozentsvayg** [comment] 2018-05-10 22:53
the kernel is old enough indeed (ubuntu trusty 3.13.0-137.186)
but the memcached binary (the one that is used for the accounting now) is statically compiled on 18.04, so it should be fine with allocators and other dependencies.

> I'll poke through and see about adding a few more counters today. If possible, should keep the current test instance running and start a second one today.

okay, the same branch?

> I'll poke through and see about adding a few more counters today. If possible, should keep the current test instance running and start a second one today.

i didn't inspect all the client code yet, but haven't seen any `gets` so far (dumping traffic for hours)

**Comment by dormando** [comment] 2018-05-11 18:34
Usually libc isn't statically linked? Or did you force it?

I didn't end up making any changes yesterday... are you making tons of stats calls anywhere? If you're not calling gets, and not calling 'stats' that often, the current counters cover all of the allocations. Every other [mc]alloc is in code you're not using (extstore), or are one-time static allocations.

Maybe by today we'll start to see some smoothing?

**Comment by mrozentsvayg** [comment] 2018-05-11 19:55
> Usually libc isn't statically linked? Or did you force it?
i did:
```
LDFLAGS = -static
LIBS = -levent -lrt
```

> are you making tons of stats calls anywhere?

it's regular scraping of 4 stats (stats, stats items, stats slabs, stats settings), average is 1 rps

> Maybe by today we'll start to see some smoothing?

not yet, another half gig since yesterday:
```
Fri May 11 12:54:43 PDT 2018
STAT bytes 2957477906
STAT total_malloced 3497000960
VmRSS:   6940032 kB
Anon:6940148
```
[stats.20180511125510.txt](https://github.com/memcached/memcached/files/1996685/stats.20180511125510.txt)

**Comment by dormando** [comment] 2018-05-11 19:58
Alright, I'll instrument the stats stuff. Any chance you could pause stats collection for 8 hours (or make it much less frequent) and see if that slows down the RSS growth?

Will ping back in a few hours. Working on a few things today.

**Comment by dormando** [comment] 2018-05-12 22:32
I've updated the conn_accounting2 branch (rebased) and it now covers everything I can think of. If it's not covered here it's definitely fragmentation from the reallocs. Some of the new stats won't align exactly, so I added a couple extra non-bytes total counters which should add up, to ensure there aren't leaked buffers.

**Comment by mrozentsvayg** [comment] 2018-05-14 19:10
sorry for the delay.
thanks, it's now running on another server.

as for the 1st instance it's only got worse. Plus 1G to RSS with only 170M in allocated :
```
Mon May 14 12:03:45 PDT 2018
STAT bytes 3113712036
STAT total_malloced 3670016000
VmRSS:   8083144 kB
Anon:8083396
```

regarding the pausing the stats, i'd try it as a last resort only.
it's getting scraped with both prometheus exporter and collectd plugin (which is a bit messier to partially disable)

**Comment by dormando** [comment] 2018-05-14 19:32
Understood. Would you mind grabbing a stats snapshot after the new instance has been up for an hour or two? ideally two snapshots a couple minutes apart. I'm going to try repro'ing as well, while back and forthing with another bug report.

**Comment by dormando** [comment] 2018-05-14 23:46
Ok: Nothing beyond initial values for suffixcache... cqbytes looks fine. No cachedump allocs (so far). number of stats allocs is equal to write-and-free, so no leaks in that short time.

That leaves: fragmentation from buffer reallocs/shrinks, and fragmentation from stats alloc/frees. Or, something libevent is doing, or some other mystery with an OS lib.

1) What version of libevent are you on? ubuntu 18.04 otherwise right?
2) I'll see if I can create a test patch with a global reused stats buffer. For the most part only one stats command can run at one time anyway. Might be a good opportunity to stick a trylock() in there and bail if too many stats commands are running at once.

Thanks again for your patience!

**Comment by dormando** [comment] 2018-05-15 02:13
ok, test patch is up in conn_accounting2. Can probably replace the original host with this if you don't want to keep adding experimental ones.

This is my best bet/guess before getting into more exotic troubleshooting... which I'll probably try really hard to reproduce myself first. Hopefully not, since I think most people only run stats calls every 30-600s.

note the patch may cause some of your stats calls to sporadically fail if they're being run at the same time. it should be unlikely. haven't decided if I want that to be a feature or not. :)

**Comment by dormando** [comment] 2018-05-15 20:52
aside: Just realized I haven't seen full `stats items` and `stats slabs` output from one of your old/long running instances. would you mind including one? looking over the post again I see that the old instance has 23g malloc'ed but only 7g in use. Just want to make sure I know what that is. (assuming it's slab calcification, which the 1.5.x shouldn't be having).

to that end stats items/slabs from the longest running 1.5.x you have would be good too.

probably not necessary but I like to have all the information possible when attempting a complicated repro like this :)

**Comment by mrozentsvayg** [comment] 2018-05-15 21:31
oldest 1.4 instance (uptime 74d):
```
Tue May 15 14:13:37 PDT 2018
STAT bytes 13043725738
STAT total_malloced 20971738144
VmRSS:  29880524 kB
Anon:29880576
```
[stats.14.txt](https://github.com/memcached/memcached/files/2006736/stats.14.txt)
[stats.items.14.txt](https://github.com/memcached/memcached/files/2006740/stats.items.14.txt)
[stats.slabs.14.txt](https://github.com/memcached/memcached/files/2006741/stats.slabs.14.txt)

oldest 1.5.7 (12d):
```
Tue May 15 14:15:51 PDT 2018
STAT bytes 9290117431
STAT total_malloced 11683233792
VmRSS:  17119008 kB
Anon:17118376
```
[stats.15.txt](https://github.com/memcached/memcached/files/2006749/stats.15.txt)
[stats.items.15.txt](https://github.com/memcached/memcached/files/2006750/stats.items.15.txt)
[stats.slabs.15.txt](https://github.com/memcached/memcached/files/2006751/stats.slabs.15.txt)

Hope to deploy the patch some time later today.
Having ~1rps for stats and avg turnaround time is no more than 1ms, it's unlikely to have an issue.
However, what do you think about a (probably configurable) retry?

**Comment by dormando** [comment] 2018-05-15 21:39
thanks!

re stats: I think I'll just bite the bullet and extend the internal cache object thing to support variable size buffers, then let it be a stack. It's unlikely to have more than 3 or 4 unless you're calling stats constantly then not reading the result buffer. Get the same behavior as now. I'll need the variable size buffers to be able to 

I used the deltas from the "two minutes apart" stats you gave me to come up with a rough repro workload.. it's doing conn_yields, sets/gets, and realloc/shrinks at roughly the same rate, along with a full set of stats output (with all items/slab classes present) twice per second. Once it got up to the item limit, it hasn't grown at all. This is with a handful of connections... will let it run a while longer then start adjusting more. This is without the stats-global test patch.

**Comment by dormando** [comment] 2018-05-15 22:59
Also, got a stats + vmRSS for the instance from yesterday? (you gave me two snapshots from the first hour).

Tried a few more things, still can't repro... mc-crusher really doesn't like using tons of connections. I got it to sort of work but it's still not growing beyond a fixed amount.

**Comment by mrozentsvayg** [comment] 2018-05-15 23:11
Sure:
```
Tue May 15 16:09:17 PDT 2018
STAT bytes 9226547391
STAT total_malloced 13065256960
VmRSS:  16599620 kB
Anon:16599808
```
[stats.20180515161011.txt](https://github.com/memcached/memcached/files/2007013/stats.20180515161011.txt)

**Comment by dormando** [comment] 2018-05-16 00:38
full /proc/`pidof memcached`/status for that one?

**Comment by mrozentsvayg** [comment] 2018-05-16 00:59
[status2.20180515175701.txt](https://github.com/memcached/memcached/files/2007152/status2.20180515175701.txt)

**Comment by dormando** [comment] 2018-05-16 03:06
Haven't had any luck so far... my total_malloced + hashtable + the various conn_* bytes counters add up to my vsize, which ends up being really close to my RSS. It hit two stable RSS peaks; once within a few minutes, then again after climbing more a few hours later. During the climb the conn_* trackers didn't move but it looks like more of the VSS turned into RSS.

After 5+ hours under a kind of broken bench with 120,000+ connection structures and a lot more conn memory allocated than yours (got my rbuf up to 3.6g!), I'm only "missing" 200m of RSS compared to the stats counters, which can pretty easily come out of alignment and allocation overhead, and it hasn't grown in hours.

Running stats commands or not didn't change anything... I'll try tuning it and run another attempt tomorrow. hopefully you can get the stats change in prod.

It's odd that your internal counters add up to ~14.867g, VSS is 17g, RSS is 16.655g.. all of the stats allocations are 1.507g... which would be close to the missing amount, but all of them were freed properly. Makes me suspicious of the system libraries again.

**Comment by dormando** [comment] 2018-05-16 19:46
Fixed the bench a lot better last night and ran it again; still levelled out with occasional small increases. I'm still confident that it's fragmentation, and I'm hoping that with the stats patch the only remaining allocations will be fixed size and cause less fragmentation. If so, I can fix the stats buffer for the next release and fix the rest slowly.

Hopefully you see at least the RSS growth rate significantly decrease with the patch.

**Comment by mrozentsvayg** [comment] 2018-05-16 21:03
Just replaced the 1st instance, running the conn-accounting2 branch, with the patched one.
Latest stats before the upgrade (uptime is ~8d):
```
Wed May 16 13:58:11 PDT 2018
STAT bytes 9568618287
STAT total_malloced 11573133312
VmRSS:  16604924 kB
Anon:16604776
```
[stats.20180516135603.txt](https://github.com/memcached/memcached/files/2010850/stats.20180516135603.txt)

**Comment by dormando** [comment] 2018-05-17 23:38
Any luck?

**Comment by dormando** [comment] 2018-05-18 01:14
Hm, hard to tell after only a day.

Think I fixed the other mystery bug I was working on, so I'm going to continue clearing other issues/PR's for the upcoming release. I'll turn the stats buffer reuse thing into a full patch for this release, but fixing the other buffers will take a few weeks at best.

Think I mentioned before but the other buffers are a lot harder to fix because ascii multigets are unbounded. Might have to come up with a compromise.

The rest should be at least better... can use larger rbuf's since they won't be stuck per connection, which would avoid a lot of the reallocs for 99% of use cases. The compromise might end up being realloc'ing and shrinking like they do now, but with larger buffers it'll just happen less often.

**Comment by mrozentsvayg** [comment] 2018-05-22 19:42
more or less the same way i'm afraid

patched:
```
Tue May 22 12:37:15 PDT 2018
STAT bytes 3119283614
STAT total_malloced 11773411328
VmRSS:  16048076 kB
Anon:16048340
```
[stats_conn_accounting2_patched.20180522123714.txt](https://github.com/memcached/memcached/files/2028274/stats_conn_accounting2_patched.20180522123714.txt)

not patched:
```
Tue May 22 12:37:37 PDT 2018
STAT bytes 3598365736
STAT total_malloced 13194231808
VmRSS:  18348512 kB
Anon:18348456
```
[stats_conn_accounting2.20180522123735.txt](https://github.com/memcached/memcached/files/2028277/stats_conn_accounting2.20180522123735.txt)

**Comment by dormando** [comment] 2018-05-22 20:06
That's disappointing.

Well, if you wouldn't mind; lets keep this issue running while I work through things. I'll finish the stats allocator reuse patch (maybe not for this upcoming release so I can let it bake) since I have to modify the object cache API to fix the other buffers anyway. It'll be a few weeks likely since I need to transition off while running some tests this week.

In the meantime, you can do some really easy experiments:

`memcached.h:#define READ_BUFFER_HIGHWAT 8192`

Double that once or twice and see if conn_reallocs and conn_shrink stats stops incrementing (or slows down considerably). I don't think you're increasing any other buffer. reallocs will still happen but shrinks should cut considerably or stop if you increase READ_BUFFER_HIGHWAT.

Downsize IOV_LIST_INITIAL from 400 to 200 (or 100, if you're sure you're not doing large ascii muiltigets since that's the only time they're really used) to cut back some RAM. (also: ITEM_LIST_INITIAL and SUFFIX_LIST_INITIAL)

What I'd expect to see is more of the "lost" memory turn into read buffer memory.

If you're feeling enterprising from there, you can adjust the initial value of the read buffer to avoid more reallocs.. however DATA_BUFFER_SIZE modifies both wbuf and rbuf, so I'd recommend:
memcached.c's dispatch_conn_new() call that uses DATA_BUFFER_SIZE, replace that with something half of or exactly your READ_BUFFER_HIGHWAT value.

If you do all of this fiddling... with the stats patch, and reallocs/shrinks are almost gone but there's still a bunch of memory unaccounted for, I'd be out of ideas and would blame a platform issue :(

I'm also looking into how bad it'd be to just use jemalloc for these connection buffers.

**Comment by dormando** [comment] 2018-05-24 19:39
That's probably fine. Personally I'd start with 16k, check it an hour or two later, then move to 32k if it's still realloc/shrinking a lot and there's memory free. Going straight to 32k also work though.

you should be able to tell quickly if it stops the realloc/shrinking within an hour, in any case.

**Comment by mrozentsvayg** [comment] 2018-05-25 02:31
after 4.5hr (16k):
```
Thu May 24 19:29:03 PDT 2018
STAT bytes 2829179163
STAT total_malloced 3867148288
VmRSS:   6105580 kB
Anon:6105696
```

```
STAT conn_reallocs 535602
STAT conn_reallocs 535976
```
[stats_conn_accounting2_patched_tuned.20180524193014.txt](https://github.com/memcached/memcached/files/2037731/stats_conn_accounting2_patched_tuned.20180524193014.txt)

**Comment by dormando** [comment] 2018-05-25 03:32
how're the reallocs per minute compared to the other instance? (at same time of day/etc)

**Comment by mrozentsvayg** [comment] 2018-06-01 23:53
after 8d:
```
Fri Jun  1 16:51:32 PDT 2018
STAT bytes 3068193338
STAT total_malloced 4137680896
VmRSS:   9336456 kB
Anon:9336548
```
[stats_conn_accounting2_patched_tuned.20180601165124.txt](https://github.com/memcached/memcached/files/2064472/stats_conn_accounting2_patched_tuned.20180601165124.txt)

**Comment by dormando** [comment] 2018-06-02 01:32
+2.2g in the connection structures. so that's 3g lost?

did you ever try 32k for the read buf and see if that changed the rate of realloc/shrinks?

I'll probably be getting back to this after next week. been doing a lot of benchmark work in the last week

**Comment by dormando** [comment] 2018-06-05 19:11
Okay... went down a rabbit hole in #328 trying to figure out an approach for fixing the connection memory, and it's a lot harder than it should be because of UDP and unbounded ascii multigets :(

I should've had you try this a while ago, but:
https://github.com/jemalloc/jemalloc/releases/download/5.1.0/jemalloc-5.1.0.tar.bz2
build this (but you don't have to install it, or just copy the lib.so somewhere),
and start memcached with:
LD_PRELOAD="/home/whatever/jemalloc-5.1.0/lib/libjemalloc.so" ./memcached

can you confirm if jemalloc is actually getting used via:
MALLOC_CONF="stats_print:true" LD_PRELOAD="/home/whatever/jemalloc-5.1.0/lib/libjemalloc.so" ./memcached
in a terminal, then ^C'ing it and it'll dump a bunch of statistics.

undo the buffer changes you made before (but maybe keep the stats change). This *should* help, but it would help a lot more if I could avoid using jemalloc for the slab memory or use some if its explicit API.

If it does help I'll look at just embedding jemalloc until I can rewire everything better. if I can tune it properly it might even allow me to malloc/free the small connection buffers at use time.

**Comment by mrozentsvayg** [comment] 2018-06-06 18:20
in 16hr with jemalloc:
```
Wed Jun  6 11:16:10 PDT 2018
STAT bytes 3926662319
STAT total_malloced 4564451328
VmRSS:   6339236 kB
Anon:6338780
```
[stats_conn_accounting2.jemalloc.20180606111634.txt](https://github.com/memcached/memcached/files/2077617/stats_conn_accounting2.jemalloc.20180606111634.txt)

**Comment by dormando** [comment] 2018-06-06 18:53
4564 + 45 + 177 + 463 + 138 + 138 + 48 + 554 == 6127 (roughly)
6339 - 6127 == 212, or ~ 3.3% overhead.

that looks a lot better, no?

**Comment by mrozentsvayg** [comment] 2018-06-07 01:03
yes, it does
in fact, 5.5% (kB=1024), but it stays like that since then:
```
# used=$((echo 'stats slabs' | nc localhost 11211|egrep total_malloced; echo stats | nc localhost 11211|egrep 'conn_[^_]+_bytes') | awk '{s+=$3}END{print s}') ; rss=$(egrep -i rss /proc/`pidof memcached.shared`/status|awk '{print $2}') ; bc -l <<< "$used*100/($rss*1024)"
95.18380355176021720754
```
i'll keep looking.
for the comparison with the patched/buffer tuned instance:
```
# used=$((echo 'stats slabs' | nc localhost 11211|egrep total_malloced; echo stats | nc localhost 11211|egrep 'conn_[^_]+_bytes') | awk '{s+=$3}END{print s}') ; rss=$(egrep -i rss /proc/`pidof memcached`/status|awk '{print $2}') ; bc -l <<< "$used*100/($rss*1024)"
63.96167497056640810079
```

**Comment by dormando** [comment] 2018-06-07 01:47
cool. looking forward to seeing the numbers tomorrow. I'll run some benchmarks when I can with some options fiddled and see how it looks. it'd be awful nice as a stop-gap if I can cut the initial value sizes way down when jemalloc is in use.

**Comment by mrozentsvayg** [comment] 2018-06-09 00:59
still looking pretty good:
```
# used=$((echo 'stats slabs' | nc localhost 11211|egrep total_malloced; echo stats | nc localhost 11211|egrep 'conn_[^_]+_bytes') | awk '{s+=$3}END{print s}') ; rss=$(egrep -i rss /proc/`pidof memcached.shared`/status|awk '{print $2}') ; bc -l <<< "$used*100/($rss*1024)"
95.96947645525850623922
```
```
Fri Jun  8 17:55:18 PDT 2018
STAT bytes 1008411407
STAT total_malloced 4625268736
VmRSS:   6568120 kB
Anon:6567292
```
[stats_conn_accounting2.jemalloc.20180608175545.txt](https://github.com/memcached/memcached/files/2086509/stats_conn_accounting2.jemalloc.20180608175545.txt)

**Comment by dormando** [comment] 2018-06-27 07:37
I assume that's been working okay for you? Running with jemalloc on your fleet is probably the answer for now.

Think the best I can do is add some documentation, and perhaps a warning on startup if setting the connection count above 10k, pointing toward said docs. At some point hopefully soon I'll be rewriting the frontend which should fix this along with pipelining issues. When that happens either it'll be fixed structurally or jemalloc gets embedded or configure time options :)

**Comment by mrozentsvayg** [comment] 2018-06-30 01:14
it's not degrading at all, still >95% memory accountable.
didn't roll it out in scale yet (hesitated as it's a bit messy to do with LD_PRELOAD)

i think i'll build it statically until it's configurable

**Comment by dormando** [comment] 2019-10-17 18:10
More than a year later, we have this work: https://github.com/memcached/memcached/pull/557
on release I should be able to close this. hadn't received any other complaints about similar problems... never really understood what the problem combination is.

**Comment by dormando** [comment] 2020-03-09 18:56
Finally closing this out.. the default memory handling in 1.6.0 for connections should be good enough without fragmentation.

**Closed by dormando** 2020-03-09 18:56 UTC
Labels: merged/fixed for next
