### ISSUE TITLE
compile error occurs

### ISSUE THREAD

**Issue by minkikim89** [memcached/memcached#654] opened 2020-04-19 03:09 UTC
OS: CentOS Linux release 7.6.1810 (Core)
Compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

Please check the error below
```
memcached.c:106:1: error: unknown type name 'evutil_socket_t'
 static void event_handler(const evutil_socket_t fd, const short which, void *arg);
 ^
memcached.c:186:1: error: unknown type name 'evutil_socket_t'
 static void maxconns_handler(const evutil_socket_t fd, const short which, void *arg) {
 ^
memcached.c:7499:1: error: unknown type name 'evutil_socket_t'
 void event_handler(const evutil_socket_t fd, const short which, void *arg) {
 ^
memcached.c:7931:1: error: unknown type name 'evutil_socket_t'
 static void clock_handler(const evutil_socket_t fd, const short which, void *arg) {
 ^
```

**Comment by dormando** [comment] 2020-04-19 03:19
libevent version?

**Comment by minkikim89** [comment] 2020-04-19 07:45
libevent-1.4.13-stable

**Comment by jefyt** [comment] 2020-04-20 10:12
@dormando Haven't considered older version of libevent when I introduced the **_evutil_socket_t_** change for Windows. I can handle fixing this issue. Fix is minimal only and can be applied to **memcached.h** file since both **thread.c** and **memcached.c** include this header file:
<pre>
#ifndef evutil_socket_t
#define evutil_socket_t int
#endif
</pre>

Just let me know.

**Comment by jefyt** [comment] 2020-04-20 11:02
I've manually confirmed 555ed28 against [libevent-1.4.13-stable](https://github.com/libevent/libevent/releases/tag/release-1.4.13-stable). Build logs:

[issue_654_nofix.log](https://github.com/memcached/memcached/files/4502970/issue_654_nofix.log)
[issue_654_withfix.log](https://github.com/memcached/memcached/files/4502971/issue_654_withfix.log)

Ubuntu, Debian, and macOS (clang) Build Logs: https://github.com/jefyt/memcached-windows/actions/runs/82759751

**Comment by dormando** [comment] 2020-04-20 21:16
centos is the wrench that keeps on breaking your shins...

Thanks and sorry; I'm pausing further development until my buildbots are redone for real this time.

**Comment by dormando** [comment] 2020-04-28 20:43
centos 7 seems to come with libevent 2.0.21.

are you running a ~7.6 version (1810?) without ever upgrading the packages?

I can't quickly tell if the base centos version would flip to libevent 2.0 after a yum upgrade or not. I just installed a builder from the latest C7.

**Comment by dormando** [comment] 2020-04-28 20:45
http://vault.centos.org/7.6.1810/os/x86_64/Packages/ (the version you claimed to have) even shows libevent 2.0. I'm confused :(

**Comment by dormando** [comment] 2020-04-28 21:01
I found a really old image kicking around: centos 7 1511, still libevent 2.0.21. You sure this isn't a centos 6 instance?

**Comment by minkikim89** [comment] 2020-04-29 06:47
Oops, sorry I didn't tell you exactly..
I installed libevent-1.4.13-stable manually. I didn't use yum.

**Comment by dormando** [comment] 2020-04-29 07:04
Thanks. Can you explain why you're running such an old version?

That's from 2009, I'm not sure it's reasonable for us to support it anymore.

**Comment by minkikim89** [comment] 2020-04-29 08:12
There is no particular reason.
I just installed the old version I've been using before.

**Comment by dormando** [comment] 2020-04-29 20:50
Could you maybe use the system version? Unless there's a specific problem you're working around?

I think instead of this we should bump the version check code to enforce 2.0 as a minimum. 1.4 is really out there.

**Comment by minkikim89** [comment] 2020-05-01 10:22
Yep. It's no problem.

**Comment by dormando** [comment] 2020-05-01 19:19
Alright, closing this out then. thanks.

**Closed by dormando** 2020-05-01 19:19 UTC
