### ISSUE TITLE
Reading from none existing key takes 5 seconds

### ISSUE THREAD

**Issue by AlBundyLoves69** [memcached/memcached#244] opened 2017-01-09 21:21 UTC
**I have a very strange behavior:** In very rare cases [1 of 1000] the `get` function needs 5 seconds to return when reading a none existing key.

Usually the execution time is so fast that it *cannot* be measured. I have no clue what causes this delay.

If you need further information please request it in a comment. I use Version 1.0.18 of http://libmemcached.org/libMemcached.html in my C++ project.

Memcached server is Version 1.4.32 of https://memcached.org/

**Comment by dormando** [comment] 2017-01-09 21:40
The server can't cause that. there's simply no way for it to block on something for any significant amount of time. This project is primarily about the server.

However, if I had to throw a guess; 5 seconds is higher than 3 seconds, which is the default SYN retry time. If you're not using persistent connections (or something about a key miss is being caused by a protocol desync and disconnect/reconnect) you might be seeing the effects of packet loss for new connections.

Take a look here and try out the script: https://github.com/memcached/memcached/wiki/Timeouts - going to close this out.

**Closed by dormando** 2017-01-09 21:40 UTC

**Comment by AlBundyLoves69** [comment] 2017-01-11 12:54
Thank you very much for your reply. I started to think about the work flow and because I am using a very well defined path of memcache I wrote my own small and effective memcache client.
