### ISSUE TITLE
segfault - memcached-proxy

### ISSUE THREAD

**Issue by sevrinrobstad** [memcached/memcached#1175] opened 2024-10-02 06:36 UTC
Hi.

We have started deploying memcached-proxy into part of our "production".

In one of the environments (with heavy traffic) I get segfaults.
```
Oct  2 05:38:27 webs213kernel: [20976742.837499] mc-worker[2186586]: segfault at 7f0ce542f000 ip 000055a23122c285 sp 00007f0ce5750610 error 4 in memcached[55a2311f5000+72000]
Oct  2 05:38:27 webs213 kernel: [20976742.837514] Code: b6 4c 24 08 49 29 c4 48 89 44 24 18 4d 01 ec 4d 39 e6 75 16 e9 b4 fd ff ff 0f 1f 40 00 49 83 c6 01 4d 39 f4 0f 84 a3 fd ff ff <45> 3a 0e 75 ee 48 8b 54 24 18 48 8b 74 24 10 4c 89 f7 44 88 4c 24

Oct  1 17:58:21 webs213 kernel: [20934737.462419] mc-worker[2060168]: segfault at 7f2fff5f9000 ip 0000564f9789b285 sp 00007f2fff92a610 error 4 in memcached[564f97864000+72000]
Oct  1 17:58:21 webs213 kernel: [20934737.462434] Code: b6 4c 24 08 49 29 c4 48 89 44 24 18 4d 01 ec 4d 39 e6 75 16 e9 b4 fd ff ff 0f 1f 40 00 49 83 c6 01 4d 39 f4 0f 84 a3 fd ff ff <45> 3a 0e 75 ee 48 8b 54 24 18 48 8b 74 24 10 4c 89 f7 44 88 4c 24
```

tried running addr2line inside the docker, but didnt give me anything useful. 

Running in docker, latest tag 1.6.31, adding routelibs (locked to specific commit "79f2a0b" just to have version control)

The logs itself only shows  (would have been great with timestamps)
```
generating an allfastest function
generating an allfastest function
Segmentation fault
```
and then startup config..

It LOOKS like it's traffic driven (since I had two segfault yesterday with traffic, none in the night, and then got one when people started waking up again), but I'm not sure. It can also be related to the slight config.lua-difference compared to the one posted in https://github.com/memcached/memcached-proxylibs/issues/11 
In the "crashing" environment we need to route all keys starting with abcd_efgh_blabla_2 to a separate memcached nodeset, so here we also have this in routes.  

```
routes{
    conf = {
        mode = "prefix",
        stop = "_2"
    },
    map = {
        -- route handler for path "abcd_efgh_blabla_2*"
        abcd_efgh_blabla = cmdmap{
            -- This covers all the set commands
            all = route_allfastest{
                children = { "large_keys1", "large_keys2" },
                stats = true,
            },
            get = route_failover{
                children = { "large_keys1", "large_keys2" },
                stats = true,
                miss = true,
                shuffle = true,
            },
            gets = route_failover{
                children = { "large_keys1", "large_keys2" },
                stats = true,
                miss = true,
                shuffle = true,
            },
        },
    },
-- default handling 
    default = route_allfastest{
        children = { "normal1", "normal2", "normal3", "normal4" },
        stats = true,
    },
-- override get/gets
    cmap = {
         get = route_failover{
             children = { "normal1", "normal2", "normal3", "normal4" },
             stats = true,
             miss = true,
             shuffle = true,
         },
         gets = route_failover{
             children = { "normal1", "normal2", "normal3", "normal4" },
             stats = true,
             miss = true,
             shuffle = true,
         },
    },
}
```

**Comment by dormando** [comment] 2024-10-02 08:56
Hey,

could be tough without the segfault info. just checking: it’s not running out of ram or anything? can you characterize the traffic at all? I have tools that can easily reproduce any type of traffic mix

**Comment by sevrinrobstad** [comment] 2024-10-02 09:50
It's not OOM. The green line is memcached-proxy (and limit is set to 1GB)
![image](https://github.com/user-attachments/assets/e8a01ff8-4122-461a-ac07-7ec6f3f0a513)

Would I be able to get more info if I made a run with memcached-debug ? I can give that a go..

the traffic is from webservices and backend services, mainly small keys except for the keys that is mapped to separate backends. These can be a couple of megabytes.

stats proxy since last restart (but not actively in production traffic):
```
stats proxy
STAT userabcd_efgh_blabla_retries 37
STAT user_cmdmap_retries 35160
STAT active_req_limit 5000
STAT buffer_memory_limit 0
STAT buffer_memory_used 0
STAT vm_gc_runs 4
STAT vm_memory_kb 508
STAT cmd_mg 0
STAT cmd_ms 0
STAT cmd_md 0
STAT cmd_mn 0
STAT cmd_ma 0
STAT cmd_me 0
STAT cmd_get 288958
STAT cmd_gat 0
STAT cmd_set 24943
STAT cmd_add 0
STAT cmd_cas 0
STAT cmd_gets 0
STAT cmd_gats 0
STAT cmd_incr 0
STAT cmd_decr 0
STAT cmd_touch 0
STAT cmd_append 0
STAT cmd_prepend 0
STAT cmd_delete 6107
STAT cmd_replace 0
```

potentially relevant stats from normal stats
STAT uptime 11043
STAT time 1727862487
STAT version 1.6.31
STAT libevent 2.1.12-stable
STAT pointer_size 64
STAT rusage_user 19.273427
STAT rusage_system 39.572942
STAT max_connections 20000
STAT curr_connections 6
STAT total_connections 22432
STAT rejected_connections 0
STAT connection_structures 31
STAT response_obj_oom 0
STAT response_obj_count 1
STAT response_obj_bytes 65536
STAT read_buf_count 17
STAT read_buf_bytes 278528
STAT read_buf_bytes_free 196608
STAT read_buf_oom 0
STAT reserved_fds 20
STAT proxy_conn_requests 320574
STAT proxy_conn_errors 2
..
STAT bytes_written 111023703
STAT limit_maxbytes 67108864

**Comment by dormando** [comment] 2024-10-02 11:21
Can you try the latest routelib commit with this?

memcached-debug can also be useful because it has extra asserts. though you’ll need the stderr to see it

test failures seem fine. Think that’s just stuff in your build env

think I saw a segfault this week when fiddling with a test config but I can’t remember what that was anymore. it might’ve been in my current dev branch

**Comment by sevrinrobstad** [comment] 2024-10-02 11:42
So you're suggesting the routelib "failover route bug" might be the culprit?
I have been running an instance with memcached-debug and latest routelib commit for 30+ minutes (without crash) now.
Will report back :)

**Comment by dormando** [comment] 2024-10-02 15:07
it’s possible it was triggering a crash but I can’t remember. it’s been very hot here and I am unusually forgetful right now :)

I’ll check everything again once I get some sleep

**Comment by sevrob** [comment] 2024-10-02 16:21
I spoke too soon, segfaulted again after +-2 hours with traffic.
This time I MAYBE got some debug info.. Did this on the host (copied the binary from the container), since the segfault is on the host.
```
kernel: [21005880.100088] mc-worker[2718963]: segfault at 7f399c330000 ip 000055944c88e2c6 sp 00007f399c644610 error 4 in memcached-debug[55944c83e000+94000]
```
I don't know anything about this, but tried my best looking at another thread debugging memcached with these tools.
000055944c88e2c6  minus 55944c83e000 , is 502c6

```
 # addr2line -e ./memcached-debug 0x502C6
addr2line: DWARF error: can't find .debug_ranges section.
proto_text.c:?

...
Reading symbols from ./memcached-debug...
(gdb) info symbol 0x502C6
process_extstore_command + 774 in section .text
 ...

Don't know if any of this helps at all.

**Comment by dormando** [comment] 2024-10-02 16:56
Looks corrupt, sadly. Docker doesn't give you a core file right?

**Comment by sevrob** [comment] 2024-10-02 17:03
Not out of the box. But If you don't find anything until tomorrow I can take a at look enabling it.

**Comment by dormando** [comment] 2024-10-02 21:32
Did you by chance try the `next` branch already? there are a couple of crash fixes sitting in there pending extended burn-in testing. I think given your traffic levels it's unlikely but it's possible the fix is in there. It's hard to trip but possible if you're setting a lot of large values at once and your network isn't very reliable.

I'm waiting for it to cool off a bit before I can turn my benchmark system back on... but the underlying API calls routelib is using are extremely heavily tested so I'm hoping it's either fixed in `next` already or it's some weird index issue in the failover code that I'm failing to remember right now.

**Comment by dormando** [comment] 2024-10-03 01:58
Started your config with some extra debugging enabled and it starts fine. Routes commands fine without trapping any errors. The underlying lua is super simple.

Hoping that the fixes in `next` are relevant here.

**Comment by dormando** [comment] 2024-10-03 02:01
Are some of the backends in your configuration dead/down when the proxy is first started? I got one debug hit there, but it doesn't seem possible to cause a problem.

**Comment by dormando** [comment] 2024-10-03 02:03
The segfault that I saw earlier this week was debug code, so not related to this.

**Comment by dormando** [comment] 2024-10-03 08:44
odd. it shouldn’t be in that code. what’s the memcached start line look like?

**Comment by sevrinrobstad** [comment] 2024-10-03 09:26
```
/usr/local/bin/memcached-debug -o proxy_config=/files/routelib.lua,proxy_arg=/files/config.lua -c 20000 -v
```

**Comment by sevrinrobstad** [comment] 2024-10-03 12:51
Hmm. still no segfaults today (running same version as yesterday, v1.6.31 with proxylibs commit 79f2a0b. Running for 6 hours in "prime time".
The difference is the parameter setting path for core dumps (sysctl -w kernel.core_pattern), and to do that i had to run the container in **privileged mode**. 

Does this make any sense to you?

**Comment by dormando** [comment] 2024-10-03 17:48
Hmm... I don't think so. what were your compile flags for memcached? The proxy isn't tested with the `--enable-seccomp` option, which would show up as a segfault (but should also print soemthing to stderr when it goes down). In general that option is awful since it's completely impossible for me to guarantee a system will work with it (they randomly add new permissions that default to off).

**Comment by dormando** [comment] 2024-10-03 17:50
Note to self: see if you can bump up priority on getting libunwind + segfault handler in.

**Comment by sevrob** [comment] 2024-10-03 18:10
Yea, I have "--enable-seccomp" on as that was in the example in devtools.
So.. I should try without that, and revert to running container in unprivileged mode then. (Still no segfaults today, all the others came after max 2 hours of prod traffic). We're getting there :)

**Comment by dormando** [comment] 2024-10-03 18:13
huh. I'll go find where that is and get rid of it. I'll also try to make that error if you build it with proxy, which I thought I had done. Sorry! Though again I'm pretty sure we made it print something before it exits the process if you get hit by seccomp, but you shared some logs that didn't show anything.

It's possible you're just getting lucky though and whatever condition was tripping things yesterday isn't there today.

**Comment by dormando** [comment] 2024-10-03 18:33
Yeah you need to start with `-o drop_privileges` to actually enable it - unless the seccomp code is causing a bug somehow, which I doubt. Can double check by looking at the output of `stats settings` and see if `drop privileges` is true

**Comment by dormando** [comment] 2024-10-03 20:21
I double checked your addr2line-foo and it looks right to me, so I think we're stuck getting a corefile :(

Can't think of any other reason why running in privileged mode would prevent a crash, so I'd have to see the stack trace.

If you do get one, the gdb commands I'm most interested in are:
`bt` - just a backtrace from the thread it apparently crashed on
`thread apply all bt` - dumps stack traces for all existing threads. needed sometimes.

... usually that's enough, but I might have further questions.

**Comment by dormando** [comment] 2024-10-03 21:50
we can also do some realtime-y fussing via the discord chat (see link at memcached.org) if we can align timezones... at which we appear to be opposites.

**Comment by sevrob** [comment] 2024-10-04 08:36
Yea I'm still waiting for a core dump, no dice so far - have been running without crash for 26 hours. (which should normally be a good thing). 
And yes, it looks like we are in different time zones. If I understand correctly you are in California, that's 9 hours behind us)
But I'll pop into the discord anyways and if needed I can work late some day next week and catch you when you wake up.

**Comment by sevrob** [comment] 2024-10-04 09:06
And 5 minutes later, it segfaulted. And I now have a coredump! yay.
Sending the results on discord PM.

**Comment by dormando** [comment] 2024-10-04 22:32
fix commited to `next`, thanks! Please give it a shot.

The tests don't always segfault during this underflow since it can eventually find the string it's looking for in memory, which is probably how I missed this initially.

**Comment by sevrinrobstad** [comment] 2024-10-07 06:33
Amazing. Testing and will report back.

**Comment by sevrob** [comment] 2024-10-09 08:27
2 days uptime, no hickups so far. Looking very good!

**Comment by dormando** [comment] 2024-10-09 22:49
Great! Remember to switch back to the non-debug binary when you're done testing.

**Comment by sevrob** [comment] 2024-10-10 12:39
Still no errors, upping the memcached-proxy vs mcrouter percentage here, and closing the issue. Again, thanx for all the help!

**Closed** 2024-10-10 12:39 UTC
