### ISSUE TITLE
Hangs with seccomp 1.5.10 on Arch / x86_64 / AWS EC2

### ISSUE THREAD

**Issue by jernst** [memcached/memcached#444] opened 2018-12-18 20:06 UTC
With `--enable-seccomp`, my memcached shared for several instances of Decko [1] refuses to respond after a while, with the process changing from
```
memcach+ 2540 1.0 0.0 414788 3200 ? Ssl 18:28 0:00 /usr/bin/memcached -l 127.0.0.1 -p 6001 -o modern
```
to
```
memcach+ 2540 0.0 0.0 0 0 ? Zsl 18:28 0:00 [memcached] <defunct>
```
It works without that build flag. I attempted [2] to get the Arch guys to build the package without `--enable-seccomp` but they redirected me upstream i.e. here. On the other hand, per README this is now marked experimental. Should distros like Arch use this flag or not?

[1] https://decko.org/
[2] https://bugs.archlinux.org/task/61116

**Comment by dormando** [comment] 2018-12-18 20:18
They should not. it doesn't work very well at the moment :( I don't think we ever advised people to turn it on, but distro's got overzealous.

If they ship the latest version, even compiling it in shouldn't cause issues since it's not enabled by default anymore.

What version are you on and was it actually enabling seccomp ('stats settings' should show it, IIRC)? If just compiling it in is causing crashes we'll need to figure that out quickly.

**Comment by jernst** [comment] 2018-12-18 20:35
Arch compiles it like this [1]:
```
  ./configure \
    --prefix=/usr \
    --enable-seccomp
  make
```
I will reopen the bug over there and ask them to remove the flag.

[1] https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/memcached

**Comment by dormando** [comment] 2018-12-18 20:37
Sorry, I was asking about a startup option. There's that compile flag, and also a start option that has to be turned on to enable it. What version are they shipping and if it's the latest, is the startup flag also turned on?

**Comment by dormando** [comment] 2018-12-18 20:38
looks like 1.5.10? simply upgrading might fix it.

**Comment by jernst** [comment] 2018-12-18 20:49
I run it like this:
```
[Unit]
Description=Memcached Daemon for Decko
After=network.target
StopWhenUnneeded=true

[Service]
User=memcached
# Remove '-l 127.0.0.1' to listen on all addresses
ExecStart=/usr/bin/memcached -l 127.0.0.1 -p 6001 -o modern
Restart=always
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=full
MemoryDenyWriteExecute=yes

[Install]
WantedBy=multi-user.target
```
So it appears I don't have the startup flag, but recompiling without `--enable-seccomp` still fixed the problem. Yes, we should get the package upgraded to 1.5.12.

**Comment by anthraxx** [comment] 2018-12-18 20:52
please try debugging and working on resolving issues when the new startup flag is enabled manually, features like seccomp are extremely useful and if nobody uses or debugs it, it will never ever get "stable". Hunting the cause and fixing the problem is the way to go, no matter if deactivated by default or considered experimental it won't magically change itself.

**Comment by dormando** [comment] 2018-12-18 20:54
@anthraxx The issues are known and complicated. Please do not ship code that is known to not work.

**Comment by anthraxx** [comment] 2018-12-18 20:56
according to you its startup param is deactivated anyway so *shrug*

**Comment by dormando** [comment] 2018-12-18 20:56
#402 - it's not a simple matter of debugging. seccomp is not cross-platform or cross-version compatible. After digging into it I'm not sure it's even designed to be used in generic end user applications, as it's completely impossible to whitelist syscalls properly since seccomp is latched to the underlying indirect implementation rather than via libc.

**Comment by anthraxx** [comment] 2018-12-18 20:58
indeed its libc and platform dependent, that's noting news and profiles need to be tested per arch as well, however it is quite frankly designed to be used for user applications like this that are potentially exposed to user input and services, that's what its designed for, limiting havoc in terms of allowed syscalls

**Comment by dormando** [comment] 2018-12-18 20:58
@anthraxx It should be disabled, yes. I just wanted to verify that the latest version worked by default as intended. folks with higher security considerations can manually test and whitelist seccomp for their particular platform; it does mostly work, it just doesn't seem like it will ever work "out of teh box" for a distro.

**Comment by dormando** [comment] 2018-12-18 20:59
Also, it's clear arch isn't even running tests since they would fail. we've only ever heard from end users. We have to come up with a different way of coping with seccomp.

**Comment by anthraxx** [comment] 2018-12-18 21:00
no reason it shouldn't, if the profiles were sufficiently tested and created for lets say x86_64 using gnu glibc there is no reason why it won't work on other distros other then they patch downstream behaviour of syscalls and then its their responsibility to fix the profiles as well

**Comment by dormando** [comment] 2018-12-18 21:01
If you want to contribute; I've linked the tracking issue earlier.

**Comment by anthraxx** [comment] 2018-12-18 21:01
thats pretty much fake news, stop assuming something arbitrary:
```
check() {
  cd ${pkgname}-${pkgver}
  make test
}
```

**Comment by dormando** [comment] 2018-12-18 21:02
Why would it be an arbitrary assumption if they're reporting issues with binaries which clearly would not pass the test suite? We've had 5 or 6 bug reports where the users repro'd failing tests. I do not work on Arch so I have no idea how they were able to install those binaries.

**Comment by anthraxx** [comment] 2018-12-18 21:03
they clearly did pass the test suite, no matter what you claim

**Closed** 2019-02-21 23:14 UTC
