### ISSUE TITLE
Memcached evicts items with extstore enabled when there are available space on disk

### ISSUE THREAD

**Issue by QuChen88** [memcached/memcached#922] opened 2022-08-13 23:38 UTC
I noticed that extstore enabled memcached upon reaching the configured memory limit, can evict items even when there are available space on the extended storage (i.e. disk file). 

My understanding is that with extstore enabled, memcached starts a separate extstore write thread upon start-up https://github.com/memcached/memcached/blob/master/memcached.c#L6021. This thread is responsible to pull cold items off of the tail of the LRU and writing it to disk when memory limit is reached https://github.com/memcached/memcached/blob/master/storage.c#L576

However, it looks like when a write command arrives, memcached would try to allocate a slab for it (See https://github.com/memcached/memcached/blob/master/memcached.c#L1648). In doing so it would evict items if the memory limit has been reached. This happens independently from the extstore write thread which moves cold items from memory to disk. See https://github.com/memcached/memcached/blob/master/items.c#L195

This is a bit counter-intuitive as I would imagine if there are available space on disk, it would spill some items to disk to free up memory instead of deleting / evicting items. Is this behavior expected? Or is it a bug?

**Comment by dormando** [comment] 2022-08-14 00:47
This is a semi-duplicate of https://github.com/memcached/memcached/issues/881 - which I haven't had time to revisit yet, but you can see more details in there.

The write thread being independent of the eviction process was a design goal: I wanted as much of memcached to continue functioning as possible if the SSD lagged or hung (which they are prone to doing, especially in cloud environments). This means the write thread and rebalancer algorithm try to keep a level of memory free as a "buffer" against incoming writes.

However IIRC the "trigger" to start writing in the first place is when memory fills, and the write thread can end up sleeping for up to a second so it can drop a few things before it gets caught up. I needed to revisit that. A lot of people work around it by setting `ext_item_age` as noted in the issue above.

Originally I assumed people would run like 30% of their cache in in memory and mostly cold data would be on extstore, but instead a lot of people run it to the limit with almost all hits going off of extstore.. which is usually still fast enough for their needs.

Another similar report was here: https://github.com/memcached/memcached/issues/794

and I have a work thread detailing thoughts on how to rewrire it here: https://github.com/memcached/memcached/issues/541#issuecomment-619457044

IIRC this would fix a few holes which are awkward in the allocation strategy, and move the "memory write buffer" for extstore from the slabber to the extstore write bufffers themselves (ie, if full it would still evict). To date nobody's sponsored the work and I've been focused on getting the proxy polished and out the door.

That said there's probably a simple fix for triggering the write thread to run before memory actually fills, I just haven't had time to revisit this yet.

**Comment by dormando** [comment] 2022-08-14 00:50
In case that ramble wasn't super clear; you should only be losing an item or two when memory fills for the _first time_, after that point the write thread should be engaged in attempting to keep some percentage of memory free.

**Comment by QuChen88** [comment] 2022-08-14 17:30
@dormando Thanks for the reply. It makes sense to have the extstore write thread being independent of the eviction process so that write traffic won't be affected by SSD lags. IMO this is a fair design choice to make in order to achieve a higher availability. 

However, here the gap is that there are scenarios when the extstore write thread is not able to keep up with the incoming write traffic, in such cases then we can have evictions when items get deleted from memcached even when there are available disk space. Like you said it might make sense to trigger the extstore write thread to run before memory actually fills. Looking at the code it should be pretty simple to do - just need to update this logic in `slabs_available_chunks()` so that we consider memory limit reached when memory usage is over X% of the `mem_limit` where X is a configuration parameter, and we can default it at something like 90%. https://github.com/memcached/memcached/blob/master/slabs.c#L706

I can help make this change if you are OK with it.

**Comment by dormando** [comment] 2022-08-14 18:16
Again, items are only potentially dropped when it _first fills_, at that point RAM is 100% full and disk is 100% empty. if it's dropping data in any other condition that's a new bug to me. I don't believe the fix is as simple as you think (so far).

Checking now, see `slabs_prefill_global()`, which is called if extstore is enabled. This sets mem_limit_reached = true when the daemon starts. The problem looks like `slabs.c:global_page_pool_size()` and `slabs_available_chunks()` are checking the memory limit directly instead of passing `mem_limit_reached`. Looking at the code it might actually be fine to just check `mem_limit_reached` here. See below.

The slab rebalancer algorithm looks at the global page pool (free memory available to any class) and makes some decisions about where to move memory. The extstore write thread only has visibility into chunks available for a slab class and how many chunks "should be free", which is set by `slab_automove_extstore`. If you just start firing off before the memory limit is reached, you still need to inform the write thread of how many free chunks to keep available.

If you simply say "well, only look at the global page pool and start flushing then", the system will struggle with moving pages in/out of the global pool constantly, and the automover may not react fast enough to maintain the pool; either way it will likely increase the amount of page moves which isn't cheap and can cause accidental evictions.

See: `slabs_automove_extstore.c:global_pool_check()`: I think the logic here will actually be fine with using `mem_limit_reached`, since it'll consider the global page pool low once it actually reaches the free target (% of free memory is already a start option! `free_ratio`). This also possibly works with the write thread since it'll only do something once chunks free is less than `target`, and `target` is initialized to zero.

`slabs_prefill_global()` was added more recently than the extstore code and I didn't retrofit the algorithm for it, which is why those two functions aren't using `mem_limit_reached`, I think. (it's been a while)

So you need to update everything carefully such that by the time the write thread needs to flush anything (memory full for the first time) it has an idea of how many chunks to keep free for each slab class.

Which is why I wrote up all those simplification notes, since it would get rid of all the per-class chunk calculations :) If you make a change, you need to run synthetic or shadowed realtime loads and watch that the change actually works and that the number of page_moves doesn't explode.

That's the secondary problem here; if you make a change I still need to validate it. This is especially hairy with anything that touches the slabber as the consequences are severe. If you do make a change and you want it included quickly I still either need sponsored time to validate it or you need to do the validation work and write it up :) I almost always spend more time validating code than writing it.

**Comment by dormando** [comment] 2022-08-18 20:39
Had a little time to look at the code more closely and run a test.

The fundamental issue is that the storage write thread only does work if chunks remaining in a class are below a `target`, and `target` is only set from the automove `memcheck` function, and that function only runs every `MEMCHECK_PERIOD`, or 60 seconds. So once the conditions are right for flushing you still have a R(0, 60) period before flushing first starts.

All of the `mem_limit_reached` stuff I talked about before is irrelevant because with prefill the memory check in those functions always fires as true.

Given I wrote this algorithm in 2017 and it has sat largely unchanged, and I have quite a lot of production experience with it now, I think proposing a simplification might get a pretty big improvement without any real downsides:

- extstore flush minimum free target is pinned at 1.5 free pages, remove the rest of the logic.
- extstore flush thread checks global page pool at top of loop
- if remaining global pool is below `free_ratio`, enable flushing
- slab automover watches for global page pool dropping below `free_ratio` and moves pages from the flushable class with the oldest tail age
- re-check algo to see how aggressively we can do the above, since it's currently pretty conservative. it should be able to aggressively fire and be fine.
- I _think_ it will be easier to avoid `evicted_nomem` cases if the automover only pulls memory off of too-large classes if it's looking for slightly below (maybe half) free_ratio

think I can just write this as a PR and ask a few of the interested parties to try some validation :)

**Comment by dormando** [comment] 2022-08-19 06:12
@QuChen88 https://github.com/memcached/memcached/pull/923 - mind trying out this PR?

It should work under _reasonable_ loads. If you benchmark a fast-as-possible write it will still likely evict objects.

This was more involved than I was expecting :( There were a few hacks around to sleep up the automover and slow down the flusher thread that also had to be adjusted.

In a test setting a 10k object every 500us it no longer causes evictions, and moves exactly one page back to the global pool every time the small slab class needs more memory. My first few attempts were really wobbly; usually over-freeing.

**Comment by QuChen88** [comment] 2022-08-19 18:24
@dormando Thanks for the PR. I will take a look

**Comment by dormando** [comment] 2022-08-24 18:00
@QuChen88 any luck? I'm trying to cut an early release this week and would love to have some more confidence including this PR :)

**Comment by dormando** [comment] 2022-08-27 00:46
going to consider this as fixed in 1.6.17

**Closed by dormando** 2022-08-27 00:46 UTC
