### ISSUE TITLE
regularly crashed with general protection faults

### ISSUE THREAD

**Issue by joerg-mi** [memcached/memcached#605] opened 2020-01-30 10:57 UTC
Hi!

we are using memcached for quite a long time - several years now - on multiple servers without problems.

Since a week memcached started to crash on four or five servers regularly with the following to messages:

memcached[24554] general protection ip:416d26 sp:7fcb66bfce50 error:0 in memcached[400000+35000]
memcached[29375] general protection ip:41862c sp:7fb75bffee18 error:0 in memcached[400000+35000]

The first one is the most frequent error; about 20 times, the second one occurred 4-5 times.

All system run CentOS release 6.10 with memcached version 1.5.21.

At the time of the first crashes we ran with 1.5.20 and we upgraded to 1.5.21 just to have the most recent version.

I used addr2line to get the code lines:

# addr2line -e /usr/lib/debug/usr/bin/memcached.debug 41862c
/usr/src/debug/memcached-1.5.21/items.c:462

 446 static void do_item_unlink_q(item *it) {
 447     item **head, **tail;
 448     head = &heads[it->slabs_clsid];
 449     tail = &tails[it->slabs_clsid];
 450
 451     if (*head == it) {
 452         assert(it->prev == 0);
 453         *head = it->next;
 454     }
 455     if (*tail == it) {
 456         assert(it->next == 0);
 457         *tail = it->prev;
 458     }
 459     assert(it->next != it);
 460     assert(it->prev != it);
 461
 462     if (it->next) it->next->prev = it->prev;
 463     if (it->prev) it->prev->next = it->next;
 464     sizes[it->slabs_clsid]--;
 465 #ifdef EXTSTORE
 466     if (it->it_flags & ITEM_HDR) {
 467         sizes_bytes[it->slabs_clsid] -= (ITEM_ntotal(it) - it->nbytes) + sizeof(item_hdr);
 468     } else {
 469         sizes_bytes[it->slabs_clsid] -= ITEM_ntotal(it);
 470     }
 471 #else
 472     sizes_bytes[it->slabs_clsid] -= ITEM_ntotal(it);
 473 #endif
 474
 475     return;
 476 }

# addr2line -e /usr/lib/debug/usr/bin/memcached.debug 416d26
/usr/src/debug/memcached-1.5.21/slabs.c:819

 811 /* CALLED WITH slabs_lock HELD */
 812 /* detaches item/chunk from freelist. */
 813 static void slab_rebalance_cut_free(slabclass_t *s_cls, item *it) {
 814     /* Ensure this was on the freelist and nothing else. */
 815     assert(it->it_flags == ITEM_SLABBED);
 816     if (s_cls->slots == it) {
 817         s_cls->slots = it->next;
 818     }
 819     if (it->next) it->next->prev = it->prev;
 820     if (it->prev) it->prev->next = it->next;
 821     s_cls->sl_curr--;
 822 }

with kind regards,

Joerg

**Comment by dormando** [comment] 2020-01-30 19:40
Hey,

Thanks so much for this! Could you include (you can send privately) a snapshot of the output from `stats`, `stats settings`, `stats items`, `stats slabs` from an instance that's been crashing?

Can you roll back to 1.5.19 to see if that clears up the issue? I had another report of this but I was unable to reproduce. We weren't able to bisect where the issue came in before the user had to revert to a much older version.

**Comment by dormando** [comment] 2020-01-31 21:27
@joerg-mi - also, if at all possible, a backtrace from a core would be fantastic (especially from the unlink_q call). For extra bonus points, the actual values of it and it->next, it->prev from the crashed out thread.

**Comment by smukil** [comment] 2020-01-31 23:23
@dormando I wonder if the 'nolock' functions can race with their lock based counterparts and momentarily break the assumption that all 'item' structs aside from the 'head' have a valid 'prev' value?

Eg: `do_item_unlink_nolock()`

**Comment by dormando** [comment] 2020-02-01 00:24
@smukil nolock is (should!) only ever be called when the particular LRU lock is already held. It's only called from lru_pull_tail (which always has the LRU lock held), and one of the crawler.c modules, which also holds the LRU lock.

do_item_unlink() always requires the item lock to be held, which I'm pretty sure is true? There are also no changes around unlink_nolock() lately. This seems like a new crash in .20, which most likely is due to that slab mover change... but need @joerg-mi to confirm if 1.5.19 was crash-free or not. Hopefully they speak up soon :(

**Comment by dormando** [comment] 2020-02-01 00:38
I have a theory that the slab mover change from #524 is causing this. I just noticed (sigh) that the 'completed' code that was added to speed things up is a bit wrong. It _should_ be advancing to the next offset if completed already _before_ the slabs lock is called. Instead it's a redundant check with the ITEM_SLABBED|ITEM_FETCHED meta flag...

The offset is calculated with math, the theory is sometimes (somewhere/somehow/some platform) the offset calculated from there wouldn't be linear. If one slab chunk gets marked as completed, but the next offset resolves to the same number, _and_ no other chunks were processed as busy during that loop, it could accidentally free the page with a linked item in it.

However, 1) usually that causes more varied crashes. 2) I wrote a test program to see if the calculated offset could ever be wrong in a few million scenarios and it passes on my platform at least.

I also ran a test with heavy slab reassignment for multiple weeks in december and didn't reproduce the crash. Not sure what the delta is here.

I'll fix the completed check to use a numeric instead of calculated offset and also properly skip the lock regardless, but would love a repro case or at least more information for this particular crash.

**Comment by dormando** [comment] 2020-02-01 01:14
I think this isit: https://github.com/memcached/memcached/pull/608

I added some printf's and manual tests and was able to cause the chunk leaks. going to hold a bit before merge/releasing. Will have to rebase the next branch and will put this out just on top of master branch.

Might also fix (or temporarily remove/comment) the completed bits just in case those are also problematic. Best case, it doesn't do anything right now anyway.

**Comment by dormando** [comment] 2020-02-02 05:10
Fix released in 1.5.22

**Closed by dormando** 2020-02-02 05:10 UTC
