### ISSUE TITLE
memcached 1.5.6 suddenly stops processing connections (CLOSE_WAIT issue)

### ISSUE THREAD

**Issue by styblt** [memcached/memcached#446] opened 2018-12-29 00:31 UTC
Hi,
I'd like to to report an issue with memcached 1.5.6 (Ubuntu 18.04.1).

`memcached                             1.5.6-0ubuntu1 `
`libevent-2.1-6:amd64               2.1.8-stable-4build1`
`Linux 4.15.0-39-generic`

The same app was working fine on Ubuntu 16.04 and memcached 1.4.25-2ubuntu1.4.

The daemon works perfectly fine until it suddenly stops processing new connections. The TCP connection is established but the daemon does not respond to any commands including "stats". The connections eventually enter the CLOSE_WAIT state and accumulate until the connection limit is reached. Restarting the daemon is the only way to fix it.

The daemon runs on 2 servers and both of them experience the same problem. The problem arises suddenly and does not seem to be caused by heavy load.

I've attached a file with detailed info about the issue including a gdb dump with the state of all the threads and a strace of the process that is accepting the connection.

Please let me know if there is any info I could add to the bug report.

[memcached-bug.txt](https://github.com/memcached/memcached/files/2715940/memcached-bug.txt)

Best Regards,
Tomas Styblo

**Comment by dormando** [comment] 2018-12-29 00:35
There were some stability bugs in 1.5.6 - any chance you could try running the latest version? (1.5.12)

**Comment by styblt** [comment] 2018-12-29 00:52
The problem only arises on our production servers once in a few days so I can't experiment with it as much as I would like. We have downgraded memcached and libevent to the versions from 16.04 to make sure it is not caused by something else in the system. I'll wait two weeks and then we may try the latest release. But I haven't found this type of bug in the release notes.

**Comment by dormando** [comment] 2019-01-11 20:41
Sorry for the long delay; just looked through your log. It does look like the workers are sitting on a lock, but without the debug symbols it's not obvious which lock. :(

If you saved a core you should be able to grab the extra symbols package, load it with gdb and get the full symbol dump without having to run a non-stripped binary (some tutorials online about how to do this).

otherwise, if you do end up trying the latest version, make sure it's not stripped so we can see the stack trace properly.

I was just looking at another bug with hash table expansion that seems to be triggerable under certain virtualized cloud instances (bizarre cpu scheduling?), but can't tell if this is the same bug or not, and the affected instances were very large with hundreds of gigabytes of RAM and dozens of worker threads.

**Comment by styblt** [comment] 2019-01-14 08:22
Hi, thank you very much for looking into the issue. I think I can now confirm the problem does not occur with memcached 1.4.25 and libevent 2.0.21 (using Ubuntu 16.04 LTS packages on 18.04 LTS).

I don't have the core dump unfortunately. I did not have enough disk space to dump it.

The server is a VMWARE VM with 24 GB RAM and 8 VCPUs.

Regards,
Tomas

**Comment by dormando** [comment] 2019-01-14 09:06
Thanks! Sadly doesn't tell me if the latest upstream has the issue or not though. I really need to put up a wiki page on how to quickly grab annotated stack traces :) I don't _think_ it's possible to annotate your current stack trace with the symbols file.

If you want I'll likely cut a new version this week with a workaround for the table expansion issue and you can try that one instead

**Comment by dormando** [comment] 2019-03-07 19:16
Hey,

Giving this a ping. Any chance you were able to verify the latest version? I haven't been able to reproduce (and nobody else has submitted a stack trace) in the meantime.

**Comment by dormando** [comment] 2019-04-04 21:41
One last poke! I'll close this out if I don't hear back in a few days.

**Closed** 2019-10-01 01:24 UTC
