### ISSUE TITLE
PHP Memcached Session

### ISSUE THREAD

**Issue by Cisar1235** [memcached/memcached#371] opened 2018-03-31 15:38 UTC
Hi, am having strange experience with php-memcached after upgraded from php-memcache serving php sessions.

Using php-memcached **occasionally** ended up with "Failed to write session data" (below). But changing it to php-memcache do not show any error. (or error not available?) Would like to make  php-memcached works. Thanks in advanced.

Environment: PHP 5.6.34, php-fpm with the following settings for php memcached sessions connecting to memcached server pool remotely. Memcached Server version 1.4.15 
Client libmemcached v1.0.16. On another machine, tried with v1.0.18 same errors.

> php_admin_value[session.save_handler] = memcached
php_admin_value[session.save_path]    = '10.2.2.1:11211,10.2.2.2:11211'
php_admin_flag[memcached.sess_consistent_hash] = on
php_admin_value[memcached.sess_number_of_replicas] = 2 
php_admin_flag[memcached.sess_binary] = on
php_admin_value[memcached.sess_connect_timeout] = 1000

> PHP Warning:  Unknown: Failed to write session data (memcached). Please verify that the current setting of session.save_path is correct (10.2.2.1:11211,10.2.2.2:11211) in Unknown on line 0

**Comment by dormando** [comment] 2018-03-31 20:02
Hey,

Any chance your issue looks like this? https://github.com/memcached/memcached/issues/282 - I've been trying to track this down.

Is that "real" memcached 1.4.15 or are you on amazon elasticache?

thanks!

**Comment by sergey-dryabzhinsky** [comment] 2018-04-03 02:30
Please try to define connection proto:
`php_admin_value[session.save_path] = 'tcp://10.2.2.1:11211,tcp://10.2.2.2:11211'`

php-memcached may be trying to use UDP proto. Which was disabled in memcached 1.5.6.

**Comment by dormando** [comment] 2018-04-07 20:17
@Cisar1235 - ping again. is this amazon elasticache you're using?

**Comment by Cisar1235** [comment] 2018-04-08 16:46
sorry for the late reply. nope its not from amazon. its a clean "real" mc server as you hv referred.

**Comment by dormando** [comment] 2018-04-08 17:45
@Cisar1235 What other information do you have? Do memcached's stats output indicate the connection limit is being hit, etc?

If you could attach a dump of 'stats' output from the time when you see errors that'd be best.

Alternatively if you can come up with a minimal .php file that reproduces this it would help a lot.

**Comment by Cisar1235** [comment] 2018-04-08 17:53
that was the added settings in php-fpm with all other standard parameters from php.ini default.

**Comment by Cisar1235** [comment] 2018-04-08 17:54
i can only assure its a test server with low load.

**Comment by dormando** [comment] 2018-04-08 18:37
@Cisar1235 ok, thanks. I ask because even under low load, if you leak client instances you can run the server out of connections and cause errors.

**Comment by Cisar1235** [comment] 2018-04-08 19:29
@dormando how does that happen? and how do check if its leaked

**Comment by dormando** [comment] 2018-04-17 17:41
@Cisar1235 ah sorry I missed your last response. If you monitor the cur_connections stat and it grows a lot higher than you expect, you probably have a leak.

**Comment by Cisar1235** [comment] 2018-04-25 14:58
am still waiting if anyone able to use clustered memcached for php session without any problem. or someone that could correct my current parameters. i really like to use clustered **php-memcached** and not _php-memcache_.

**Comment by dormando** [comment] 2018-04-26 04:05
@Cisar1235 what OS/distro were you using?

You never confirmed if you were hitting connection limits before?

**Comment by dormando** [comment] 2018-05-09 05:03
@Cisar1235 ping again

**Comment by dormando** [comment] 2019-04-27 08:29
:'( guess I'll close this. This PHP mystery is infuriating.

**Closed by dormando** 2019-04-27 08:29 UTC
