### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [memcached/memcached#386] opened 2018-06-08 11:03 UTC
[The variable “`caught`”](https://github.com/memcached/memcached/blob/dbb7a8af90054bf4ef51f5814ef7ceb17d83d974/timedrun.c#L10 "Update candidate") should [use the data type “`sig_atomic_t`”](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers).

**Comment by VadimPushtaev** [comment] 2018-06-27 22:43
This code is somehow naive anyway. For instance, if you send the second signal immediately after the first one, that first signal can be ignored due to races.

I'm not sure it is worth to be fixed since that is used for tests only.

***

On my machine, the problem can be reproduced like this. First, create a script to be run:

```perl
#!/usr/bin/env perl

use strict;
use warnings;

$SIG{INT} = sub { print "INT\n" };
$SIG{TERM} = sub { print "TERM\n" };

sleep 1 while 1;
```

Then run it with `timedrun`:

```
./timedrun 100 ./script.pl
```

Now send two different signals
```
perl -e '$x = shift; kill("TERM", $x) && kill("INT", $x)' 12345
```

If `timedrun` is not nice enough, it works fine:

```
$ ./timedrun 100 ./script.pl
TERM
TERM
```

But we can get a different result by simply lowing priority:

```
$ nice -n 10 ./timedrun 100 ./script.pl
INT
```

**Comment by dormando** [comment] 2018-06-28 01:15
Yeah the report is pedantic; this project gets a lot of static analyzer noise. I've marked this as "help wanted" since there's no real harm in fixing it, but anyone can do it :)

**Comment by danielschemmel** [comment] 2019-11-09 21:19
The field [settings.sig_hup](https://github.com/memcached/memcached/blob/1939cf9edc0656f7b1cfab6365f313b56b07a333/memcached.h#L401) should also be similarly using `sig_atomic_t`.

**Comment by dormando** [comment] 2019-11-09 21:25
please open new issues/pr's.

**Closed** 2020-01-21 23:08 UTC
Labels: help wanted
