### ISSUE TITLE
slab auto-mover anti-favours slab 2

### ISSUE THREAD

**Issue by mjhags** [memcached/memcached#677] opened 2020-05-13 14:11 UTC
Apart from production loads I've not been able to reproduce this behaviour with a test, so this is just observed behaviour, for which I apologise because I dislike such bug reports too :(

We use memcached heavily for caching, where cache object sizes vary a lot, so most slabs get populated well, and typically we run memcached with full or near full cache, evicting continuously as a matter of course, which is fine.

But the sort of slab pattern shown below is one I've seen happen a lot.  This is from a long running 1.5.12 version, with pretty much default options so auto-move has seen a lot of action.

You'll see that poor old slab 2 is way out of line with the other slabs, evicting hard with very short retention time.

Interestingly I find that if I try to manually reassign pages with a "slabs reassign -1 2" it does not work well, slab 2 tends to get an extra page, and then often very shortly later gets it taken away again.  The best strategy I've found to work around this is to explicitly steal pages from the slab with the most pages.  But even then after a while slab 2 still tends to lose its pages again, only by switching off the auto-mover can I stop that, but that's not something I want to do, because the auto-mover is very useful as the object size distribution tends to move around over time.

Feels as if something is off with the auto-mover strategy here?
```
 #  Item_Size  Max_age   Pages   Count   Full?  Evicted Evict_Time OOM
  1      96B        65s       1      13      no        0        0    0
  2     120B       859s      12  101675      no 1111968844      859    0
  3     152B   1659607s     529 3635434      no 85690307  1659505    0
  4     192B   1959105s    1488 8121066      no 121855414  1958008    0
  5     240B   1970157s    9306 40649963      no 532225918  1970139    0
  6     304B   1969892s   13207 45546584      no 772434412  1969788    0
  7     384B   1969879s   13592 37104025      no 262466561  1969847    0
  8     480B   1970931s   20927 45704566      no 255613273  1970931    0
  9     600B   1972349s   17570 30694788      no 190660089  1972349    0
 10     752B   1998325s   18878 26315931      no 170392332  1998325    0
 11     944B   1972610s   32811 36420208      no 201718623  1972610    0
 12     1.2K   1972439s   37971 33604334      no 173829153  1972439    0
 13     1.4K   2043535s   21788 15425901      no 82356826  2043534    0
 14     1.8K   2009197s    1495  843179      no 34658932  2009200    0
 15     2.3K    402141s      46   20746     yes 25126460   205116    0
 16     2.8K   2036542s    4102 1480821      no 35900304  2036541    0
 17     3.5K   1971126s   31257 9002015      no 69675613  1971126    0
 18     4.4K   1970435s   28465 6546949      no 81708667  1970435    0
 19     5.5K   1970291s   13225 2433399      no 51844206  1970292    0
 20     6.9K    759130s    1166  171401      no  6942599   759128    0
 21     8.7K   2448390s       2     235      no   214855  2455997    0
 22    10.8K  17642001s       2      75      no    90405   122249    0
 23    13.6K  17723915s       2     115      no 11653861   416221    0
 24    16.9K  17621517s       2      87      no 38943946   414306    0
 25    21.2K  17621958s       2      64      no 11276385   363682    0
 26    26.5K  17621939s       2      33      no   986909   337650    0
 27    33.1K  17627551s       1       2      no      429     5020    0
```
For completeness here's the stats output too:
```
localhost:11211   Field       Value
         accepting_conns           1
               auth_cmds           0
             auth_errors           0
                   bytes 250303570761
              bytes_read 67753822799024
           bytes_written 295264937381406
              cas_badval           0
                cas_hits           0
              cas_misses           0
               cmd_flush           0
                 cmd_get 198875839799
                 cmd_set 66089652289
               cmd_touch           0
             conn_yields    36403479
   connection_structures        1103
   crawler_items_checked 2964743752566
       crawler_reclaimed  2765169795
        curr_connections         649
              curr_items   343929103
               decr_hits           0
             decr_misses           0
             delete_hits           0
           delete_misses           0
         direct_reclaims  4331997512
          evicted_active         233
       evicted_unfetched  3535040165
               evictions  4330622680
       expired_unfetched  1592350194
             get_expired    55961700
             get_flushed           0
                get_hits 188633391219
              get_misses 10242448580
              hash_bytes  4294967296
       hash_is_expanding           0
        hash_power_level          29
               incr_hits  3074260505
             incr_misses        1199
                libevent 2.0.21-stable
          limit_maxbytes 280860033024
     listen_disabled_num           0
        log_watcher_sent           0
     log_watcher_skipped           0
      log_worker_dropped           0
      log_worker_written           0
       lru_bumps_dropped           0
     lru_crawler_running           0
      lru_crawler_starts     6696422
  lru_maintainer_juggles 37105337420
       lrutail_reflocked        3131
            malloc_fails           0
         max_connections        8192
           moves_to_cold 17259815838
           moves_to_warm  2891877815
        moves_within_lru    37650113
                     pid       14923
            pointer_size          64
               reclaimed    61392198
    rejected_connections           0
            reserved_fds          20
           rusage_system 3122520.712456
             rusage_user 2968703.518491
   slab_global_page_pool           0
slab_reassign_busy_deletes           0
slab_reassign_busy_items  2440813655
slab_reassign_chunk_rescues           0
slab_reassign_evictions_nomem  2437116572
slab_reassign_inline_reclaim  1824133490
   slab_reassign_rescues   969198347
   slab_reassign_running           0
             slabs_moved     1205988
                 threads           4
                    time  1589378981
time_in_listen_disabled_us           0
       total_connections    41110118
             total_items 67426485848
              touch_hits           0
            touch_misses           0
                  uptime    24810089
                 version      1.5.12
```

**Comment by dormando** [comment] 2020-05-13 19:24
Thanks! Interesting. I don't think much has changed in the mover algo since 1.5.12. That definitely looks odd.

The automover algorithm(s) have python implementations in the scripts/ directory of the release tarball. They're designed so you just run the script against an instance; it disables the internal algo and runs the python version, which should be identical. Do you have any interest in trying out this script to tune or look at verbosity prints to debug what's going on? Or at least see if it makes the same decisions as the C one.

Another thing is the new: https://github.com/memcached/mctester - which I'm extending this week. It's designed to help reproduce production workloads. Unless I get a repro workload or eyeball the bug there won't be too much I can do since I don't have access to your production :)

How often do you run into this?

**Comment by mjhags** [comment] 2020-05-14 07:51
I'd forgotten about the python version, that's a great idea, I'll have a play.

I'm seeing this quite a lot actually, got about 100 boxes with large memcached instances, of which about 20 are in this sort of state.

**Comment by dormando** [comment] 2020-05-14 09:03
Should be easy to spot then, I hope. Lets get this figured out :) The verbose option should print a good amount of detail right off the bat. Only caveat is once you shut down the script I don't think it automatically re-enables the internal algo, so just remember to do that before walking off. The script does automatically disable it when starting up.

Also, running `watch sysevents` on the daemon has some but not many prints about when the internal algo is making decisions, for what it's worth.

**Comment by mjhags** [comment] 2020-05-14 14:52
So interestingly having added a little more verbose output to the python code, I'm coming to the conclusion that in part there is an artefact of the work load, but also the drawback of sliding windows.  What's happening is that load and evictions on slab2 for some reason are somewhat bursty, which means it can evict for 10 or 15 seconds, then stop evicting for next 30 seconds or so.

This means that the default 30 sliding window (on 1s intervals) gets fooled into thinking that even though slab2 is the youngest by far its not evicting enough to be a candidate for a move.  Then slab2 ends up being stuck in a somewhat vicious cycle that it can never break out of.  If I drop the window to 10 slots, still with a 1s interval, it actually looks much happier in our load case.

3 servers in the same load group where the 1st and 3rd are running python mover with 10 slot window are starting to look much happier compared to the 2nd (this is memcached display output for slab 2 only):

2     120B      5240s      22  181761      no 4043440802     2885    0
2     120B          69s        4   22017       no 1114132977       54    0
2     120B      5528s      18  149619      no 926377566     4007    0

I'll have a stab at reproducing this locally now and see if I can amend the the sliding window algorithm to be less easily fooled by bursty load.

**Comment by dormando** [comment] 2020-05-14 21:25
Cool! Looking forward to your results. I'm pretty busy at the moment so can't investigate myself for a few days.

Surprisingly, I basically made up that page mover algo off the top of my head and we received almost no bug reports or feedback since then.

IIRC window size and ratio are starttime options for the daemon. Think there's a runtime cmd for it too.

**Comment by dormando** [comment] 2020-05-18 19:43
Any luck?

**Comment by mjhags** [comment] 2020-05-19 08:00
The modifications I've made to the python version seem to be helping my use case a fair bit.  Essentially extends the rolling window logic to also capture the size of the evictions in each slot, and then at any point you can see over the window that if one slab has a significant proportion of the total evictions it becomes a candidate for a move.  

Its probably a somewhat pathological case, where there is a huge burst of evictions on the slab followed by a fairly quiet period.  I guess that for lower slabs this is more of an issue because the ratio between entries and pages is higher.  A test for this case is to fill up all the memory using higher slabs, then send short bursts of writes for short periods at, say, slab2.  Previously it would never get more space than its initial page allocation because it never has sustained traffic to be flagged for moves, so would always be short time evicting.

The change to the python code is tiny, I'll have a look at a c version next.

**Comment by dormando** [comment] 2020-05-19 08:12
I think an earlier version of the algo was weighting the evictions by chunks per page but that was hitting a different edge case. Struggling to remember but that was a long time ago.

**Comment by dormando** [comment] 2020-05-29 06:47
Fwiw, feel free to just post up your python changes. I can deal with the C stuff if it's harder, or at least take a look at what's changed so far. :)

Thanks!

**Comment by mjhags** [comment] 2020-05-29 13:52
Hiya, got a bit buried in work, I did fork and start looking at the c version, but got sidetracked.  The attached patch on the python script is, however, now running on a few dozen of our instances and all are now in much better balanced state.  So for us this modification seems to be working well.

[memcached-automove.patch.txt](https://github.com/memcached/memcached/files/4702131/memcached-automove.patch.txt)

**Comment by dormando** [comment] 2020-07-01 20:26
@mjhags any chance you could quickly put a real PR up? It's hard to credit you properly otherwise.

finally giving this a stricter look. In the original code it would set the target based on there being evictions seen (at all) during half of the window. You preserved this by adding window_check_count to count total non-zero values. You then change the 'ev' stat in the window to be the ratio of evictions in that slab vs the total evictions seen in that window.

then, if more than 25% of the total evictions in that window are in that slab class, it gets targeted for a new page.

Did you also change the window size at all? I'm guessing this makes it respond more to bursts; since a lot of evictions within a single window would trigger a page move now.

I'll think about this a bit more, but I'll do the C bits if you just open a PR for the python one, for proper attribution.

**Comment by mjhags** [comment] 2020-07-02 13:50
https://github.com/memcached/memcached/pull/695 submitted. Yep that's the extra control, no change to the window required for me.  This basically sits alongside the existing logic as a secondary decision point.

**Comment by dormando** [comment] 2020-07-02 23:57
@mjhags thanks! I've merged that into `next` and done the C bits, also pushed to `next`. Any chance you could test the branch before the next release?

**Comment by mjhags** [comment] 2020-07-03 10:12
Had a play and that works well for me.

I have a very basic test rig that runs a small memory, 64m, memcached, fairly slowly fills it with continuous writes on higher slabs, and a second writer pushes stuff in bursts to slab2.  Without the fix slab2 sits with 1-2 pages all the time and has a very short evict time, with the fix it pushes more pages into slab 2 and evict-time is fairly good for all slabs.  Bit belt-and-braces and crude, so not really ideal for a unit test framework.

**Closed** 2020-09-04 22:50 UTC
Labels: help wanted, merged/fixed for next
